In [1]:
import theano
#例子1
#数值：iscalar(int类型的变量)、fscalar(float类型的变量)
# 一维向量：ivector(int 类型的向量)、fvector(float类型的向量)、

#二维矩阵：fmatrix(float类型矩阵)、imatrix（int类型的矩阵）

#三维float类型矩阵：ftensor3  

#四维float类型矩阵：ftensor4
#定义一个int类型的数值
x=theano.tensor.iscalar('x')
#定义y^3
y=theano.tensor.pow(x,3)
#定义x为输入，y为输出
f=theano.function([x],y)
print(f(2))
print(f(5))


8
125


In [2]:
#例子2:函数示例
import theano
x=theano.tensor.fscalar('x')
y=1/(1+theano.tensor.exp(-x))
f=theano.function([x],y)
print f(3)


0.952574133873


In [4]:
#coding=utf-8
#例子3:function使用示例(既有因变量又有自变量)
import theano
#定义2个自变量fscalar后面加s
x, y =theano.tensor.fscalars('x', 'y')
z1=x+y
z2=x*y
f=theano.function([x,y],[z1,z2])
print f(2,3)

[array(5.0, dtype=float32), array(6.0, dtype=float32)]


In [5]:
#例4-1用theano.grad()求偏导数
#coding=utf-8
import theano
x=theano.tensor.fscalar('x')
y=1/(1+theano.tensor.exp(-x))
dx=theano.grad(y,x)
f=theano.function([x],dx)
print f(2)
print f(4)


0.104993581772
0.0176627058536


In [13]:
#例子4-2:贡献变量
#coding=utf-8
import theano
import numpy
#随机生成一个矩阵
A=numpy.random.randn(3,4);
#从A创建共享变量x
x=theano.shared(A)
#通过get_value()、set_value()可以查看、设置共享变量的数值
print x.get_value()
#print x.set_value()出错


[[-0.07278118  1.32234253 -0.51439524 -1.27821494]
 [ 2.62634206  0.72806684  0.41380656 -0.50910207]
 [-0.25457649  0.40410296 -1.31388972 -0.15118738]]


In [18]:
#例子4-3:更新共享变量参数
 #coding=utf-8  
import theano
#定义一个共享变量w使其等于1
w=theano.shared(1)
x=theano.tensor.iscalar('x')
#定义函数自变量为x，因变量为w，当函数执行完毕后，更新参数w=w+x
f=theano.function([x],w,updates=[[w,w+x]])
#函数输出为w
print f(3)
#输出w+x
print w.get_value()


1
4
